### ISSUE TITLE
App icon is missing from the Linux Mint menu

### ISSUE THREAD

**Issue by cpfotiadis** [adrienverge/PhotoCollage#100]
Hello. The app icon does not appear in the Linux Mint menu. When I open the app, the icon appears normally in the panel, but it doesn't appear in the menu. I restarted the computer but again the icon does not appear in the menu. I don't know if the same problem exists in other linux distributions, I only tried in Linux Mint.

![Screenshot from 2023-10-30 17-14-00](https://github.com/adrienverge/PhotoCollage/assets/148790327/307b66be-4cfa-4cce-a390-9d167150dee6)

**Comment by adrienverge** [comment]
Thanks for reporting this. I think the icon definition is done inside `data/photocollage.desktop`. Maybe it's now required to set it elsewhere. Any help and code contribution to fix this will be appreciated!

**Comment by guynux** [comment]
Icon also missing in the menu on fedora 39 silverblue with flatpak

**Comment by ChrisLauinger77** [comment]
I fixed the svg and made a PR

**Comment by adrienverge** [comment]
Hello, I fixed the SVG image in https://github.com/adrienverge/PhotoCollage/pull/111. This will be in the next release.

(@ChrisLauinger77 thanks for you PR, but it does not "fix" the SVG, it removes the real SVG vectorial data and replaces it with a PNG image.)
