### ISSUE TITLE
import urllib.parse in photocollage/gtkgui.py doesn't work with Python 2.7

### ISSUE THREAD

**Issue by mpeterma** [adrienverge/PhotoCollage#11]
Hello,

there seems to be an issue with running PhotoCollage 1.3 on Python 2.7. The urllib.parse import works different compared to Python 3.

Would it be possible to fix the import in gtkgui.py in a way that it works for both versions?

Thanks & kind regards,
Matthias

**Comment by adrienverge** [comment]
Hi, thanks for pointing this. Does commit 98f9b4f solve the problem?

**Comment by mpeterma** [comment]
Hello, thanks for the solution - the aforementioned commit fixes the problem.

**Comment by adrienverge** [comment]
Thanks, closing this.
