### ISSUE TITLE
Program hangs when saving

### ISSUE THREAD

**Issue by hellocatfood** [adrienverge/PhotoCollage#13]
I'm using PhotoCollage from commit 98f9b4f8ac on Ubuntu 15.04. If a user goes to save an image and a file type isn't specified then the program hangs whilst trying to save.

**Comment by frischnetz** [comment]
Same here. It hangs when saving. It's practically unusable. Ubuntu 15.10.

**Comment by adrienverge** [comment]
Hi, can you confirm the program hangs when "a file type isn't specified"? What happens when you select a file type from the drop-down list? When you explicitly add `.jpg` or `.png` to the filename?

**Comment by hellocatfood** [comment]
When a file type is specified then the image is saved.
