### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by herm** [adrienverge/PhotoCollage#16]
Try to install using pip failed on my system. You probably need to add a dependency on DistUtilsExtra. (Solved using apt-get install python3-distutils-extra)

After installing it fails to start with another missing dependency (PIL). (Solved using apt-get install python3-pil).

```
# pip3 install photocollage
Downloading/unpacking photocollage
  Downloading photocollage-1.3.0.tar.gz (186kB): 186kB downloaded
  Running setup.py (path:/tmp/pip-build-j8cqyb84/photocollage/setup.py) egg_info for package photocollage
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-build-j8cqyb84/photocollage/setup.py", line 6, in <module>
        from DistUtilsExtra.command import build_extra, build_i18n
    ImportError: No module named 'DistUtilsExtra'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip-build-j8cqyb84/photocollage/setup.py", line 6, in <module>

    from DistUtilsExtra.command import build_extra, build_i18n

ImportError: No module named 'DistUtilsExtra'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-build-j8cqyb84/photocollage
```

```
$ photocollage 
Traceback (most recent call last):
  File "/usr/local/bin/photocollage", line 23, in <module>
    from photocollage import gtkgui
  File "/usr/local/lib/python3.4/dist-packages/photocollage/gtkgui.py", line 30, in <module>
    from photocollage import APP_NAME, artwork, collage, render
  File "/usr/local/lib/python3.4/dist-packages/photocollage/render.py", line 24, in <module>
    import PIL.Image
ImportError: No module named 'PIL'
```

**Comment by salvadhor** [comment]
> Try to install using pip failed on my system. You probably need to
> add a dependency on DistUtilsExtra. (Solved using apt-get install
> python3-distutils-extra)
> 
> After installing it fails to start with another missing dependency
> (PIL). (Solved using apt-get install python3-pil).
> 
> ```
> # pip3 install photocollage
> Downloading/unpacking photocollage
>   Downloading photocollage-1.3.0.tar.gz (186kB): 186kB downloaded
>   Running setup.py
> (path:/tmp/pip-build-j8cqyb84/photocollage/setup.py) egg_info for
> package photocollage Traceback (most recent call last): File
> "<string>", line 17, in <module> File
> "/tmp/pip-build-j8cqyb84/photocollage/setup.py", line 6, in <module>
> from DistUtilsExtra.command import build_extra, build_i18n
> ImportError: No module named 'DistUtilsExtra' Complete output from
> command python setup.py egg_info: Traceback (most recent call last):
> 
>   File "<string>", line 17, in <module>
> 
>   File "/tmp/pip-build-j8cqyb84/photocollage/setup.py", line 6, in
> <module>
> 
>     from DistUtilsExtra.command import build_extra, build_i18n
> 
> ImportError: No module named 'DistUtilsExtra'


Thank you for feedback, I'll fix it soon.

best regards,

-- 
Dariusz

**Comment by SalvatoreT** [comment]
@herm @salvadhor This is the closest I got before I hit my own wall (but I was so close!).

## Install GNU gettext
I found [this helpful chain](https://gist.github.com/mbillard/1647940) for setting up GNU gettext which is needed for intltool.

```
# from a temporary directory (or whatever)
wget https://ftp.gnu.org/pub/gnu/gettext/gettext-latest.tar.gz
tar -zxvf gettext-latest.tar.gz
rm gettext-latest.tar.gz # if you want to be tidy
cd gettext-0.19.5.1/      # your version number may be different
./configure                    # set up everything (this takes a while)
make                            # build everything (also takes a while)
make install                  # install (surprisingly doesn't take that long)
```

## Install Everything Else

```
# from the PhotoCollage directory
pip install https://launchpad.net/python-distutils-extra/trunk/2.38/+download/python-distutils-extra-2.38.tar.gz
brew install intltool py3cairo
pip3 install gi
python3 setup.py install
```

## My problem
```
PhotoCollage (master) $ python3 bin/photocollage
Traceback (most recent call last):
  File "bin/photocollage", line 23, in <module>
    from photocollage import gtkgui
  File "/usr/local/lib/python3.4/site-packages/photocollage/gtkgui.py", line 23, in <module>
    from gi.repository import Gtk, Gdk, GObject
  File "/usr/local/lib/python3.4/site-packages/gi/__init__.py", line 39
    print url
            ^
SyntaxError: Missing parentheses in call to 'print'
```

Let me know if you have another/better way, please.

**Comment by rolisz** [comment]
@SalvatoreT You probably installed a Python 2 library somehow, instead of the Python 3 one.

**Comment by adrienverge** [comment]
Hi,

Looks like everything works when pre-installing dependencies mentioned in the README, so I close this issue.

By the way, version 1.4.0 (just released) does not depend on `python3-distutils-extra` anymore.

**Comment by ocram** [comment]
With the latest https://github.com/adrienverge/PhotoCollage/commit/bb986259c1123a3080374d6de9be1c354762907f on Ubuntu 18.10, it was still necessary to add the following two dependencies:

```bash
$ sudo apt-get install python3-distutils
$ sudo apt-get install python3-pip
```

This might be obvious to Python developers, but it should probably be documented as a dependency.
