### ISSUE TITLE
Enhancement : swap two photos

### ISSUE THREAD

**Issue by Nico207** [adrienverge/PhotoCollage#2]
Hello,

it would be great if we can swap two photos by clicking on it.

| _Photo 1_ | Photo 2 |
|------------|-----------|
| **Photo 3** | **_Photo 4_** |

If click on photo 1 then on photo 4 :

| _Photo 4_ | Photo 2 |
|------------|-----------|
| **Photo 3** | **_Photo 1_** |

**Comment by adrienverge** [comment]
Done! This feature is now available in PhotoCollage 1.2.1.
