### ISSUE TITLE
Please add a way to set desired aspect ratio

### ISSUE THREAD

**Issue by jhawkesworth** [adrienverge/PhotoCollage#24]
I would like to be able to create European sized posters (A3, A4 etc).
It would be great to be able to set the aspect ratio about 1:1.414 for A4, for example so that the posters are the right shape for the destination printout.

Many thanks!

**Comment by adrienverge** [comment]
Sorry, what you're asking is not possible, because the width / height ratio is determined by the input images. You can only adjust the ratio *grossly* by influencing the placement algorithm to force a thicker (or taller) image by using the two buttons with arrows.

**Comment by jhawkesworth** [comment]
Ok. would be nice if  you could perhaps overlay a desired output size, even if it just meant cropping the generated image to get the size you want.  As long as you could move the generated image around and see the effect that would do the trick.

It would probably be a lot of extra work though..

**Comment by adrienverge** [comment]
Hi @jhawkesworth,

I just finished implementing version 1.4.0, in which the destination ratio (both width and height) can be set precisely.

I hope you'll like it. By the way thanks for the idea!

**Comment by tomplus** [comment]
Hi @adrienverge 

Fantastic! New feature works very well.

Thanks a lot.

Tom

**Comment by jhawkesworth** [comment]
This is great news, thank you so much!
I look forward to trying it out.

**Comment by ocram** [comment]
The support for precise dimensions (where width and height can be specified freely) is really great. But I’m not sure whether providing this *instead* of the old solution is a net positive. If the old approach worked without cropping pictures, it should really be stored as an option, if that is possible. In many cases, having a composed collage where one dimension doesn’t fit perfectly is much more desirable than having all individual pictures cropped.
