### ISSUE TITLE
Is possible to generate photo collage from command line?

### ISSUE THREAD

**Issue by ghprod** [adrienverge/PhotoCollage#25]
Hi..

is it possible to generate photo collage from command line?

Thanks

**Comment by adrienverge** [comment]
Hi,

No, sorry, this is not currently possible.

**Comment by ghprod** [comment]
Thanks for your reply .. closed :+1:

**Comment by akuma34** [comment]
Is there a fundamental limitation that it wont work from NON GUI ( e.g it is using GUI as rendering engine). i not then its a matter of code change? I can do the code change, if that needs to be done unless project is using GUI as image rendering engine.
