### ISSUE TITLE
Change paper size?

### ISSUE THREAD

**Issue by rbroberts** [adrienverge/PhotoCollage#29]
I don't see any way to set the paper size to values other than those in the drop down. I'm running 1.4.2 on Fedora 23, and I have no choices for Ledger (11"x17") and don't see how to add a new size. Other sizes would also be useful, e.g., "standard" poster size of 18"x24", to send out for printing.

**Comment by adrienverge** [comment]
Hi @rbroberts,

You can set whatever output size you want by directly writing in the dimensions fields. The values are set in pixels.

However the template list (drop-drown menu) is currently not customizable, sorry.

**Comment by ocram** [comment]
It might make sense to add a few more entries to the helpful list of size templates. This won’t hurt, and will make the application even more convenient for even more use cases.

In addition to the example suggested above, right now there are only A4 and A3 from that system of paper sizes:

A4 Landscape = 3508 × 2480
A4 Portrait = 2480 × 3508

A3 Landscape = 4961 × 3508
A3 Portrait = 3508 × 4961

But for printing on canvas, etc., the larger sizes A2 and A1 are also really common. It would be great if these could be added, which shouldn’t be too much of a hassle:

A2 Landscape = 7016 × 4961
A2 Portrait = 4961 × 7016

A1 Landscape = 9922 × 7016
A1 Portrait = 7016 × 9922
