### ISSUE TITLE
CLI Use case

### ISSUE THREAD

**Issue by blazeeboy** [adrienverge/PhotoCollage#30]
I have a situation where i need to generate a Collage form a set of photos, it should be part of a larger application so it should generate this collage from CLI only, I don't need to tweak the result, just push my parameters to the scripts and get an image collage as a result.

can I do something like this with PhotoCollage, and if not what modifications you think could be done to the project to achieve this CLI interface? I'm thinking that instead of redoing the same thing in my application just enhance your project and invoke it from mine.

**Comment by adrienverge** [comment]
Hi @blazeeboy!

Contributions are welcome if carefully done.

If you need some advice to start, here is what I would do:

1. create `bin/photocollage-cli` and `photocollage/cli.py` files

2. re-use `UserCollage` from `gtkgui.py`

3. use `argparse` to achieve a signature like:

   ```
   photocollage-cli --output-file OUTPUT.JPG
                     --output-size 4000x3000
                     [--border-color '#FFFFFF']
                     [--border-width 3]
                     IMG.JPG IMG2.JPG...
   ```

**Comment by blazeeboy** [comment]
Thanks @adrienverge I will try to do it.
