### ISSUE TITLE
AppData file can't be used :(

### ISSUE THREAD

**Issue by hughsie** [adrienverge/PhotoCollage#5]
Hey,

Thanks for creating an AppData file -- unfortunately the Fedora AppStream builder isn't using it because:

    photocollage.appdata.xml license 'GPLv2+' invalid

It's really useful if you can use a SPDX ID content licence from the Debian approved list[1]  -- if you *have* to use GPL for whever reason, you need use an actual SPDX identifier[2], e.g. "GPL-2.0+" -- this is fine for Fedora. Thanks! 

[1] http://people.freedesktop.org/~hughsient/appdata/#metadata_license
[2] http://spdx.org/licenses/

**Comment by adrienverge** [comment]
Thanks for feedback Hugh. I've updated the license ID, and also added keywords and categories to the .desktop file. It now validates when using `appstream-util validate data/photocollage.appdata.xml`.

**Comment by hughsie** [comment]
Great, thanks for the speedy fix!
