### ISSUE TITLE
Filenames with umlauts cannot be imported

### ISSUE THREAD

**Issue by martin-ueding** [adrienverge/PhotoCollage#63]
I noticed that I cannot drag and drop images from a directory containing an umlaut (`Käsekuchen`) into the program, it would tell me that the file does not exist and show the path in question in apparently different encoding, I guess `latin1`. This means that somewhere the filename gets treated with the wrong encoding. Renaming the directory to `Kaesekuchen` fixed it.

**Comment by adrienverge** [comment]
Hi @martin-ueding, thanks for reporting this! Any help or contribution to fix this will be welcome.

**Comment by martin-ueding** [comment]
To give a bit more context, dragging a file from the following directory does not work:

    /home/mu/Bilder/Bilder_Datenbank/2019/20190322-Selbstportrait_Römerstraße

Then I am presented with this error message:

![Bildschirmfoto_015](https://user-images.githubusercontent.com/976924/64067436-bccfbd80-cc28-11e9-81c3-075d391135f4.png)

On my Fedora 30 system this program seems to be launched with Python 3, so that is good regarding the encoding handling.

I am now going through version bb986259c1123a3080374d6de9be1c354762907f.

The GUI dialog that pops up is created in `photocollage/gtkgui.py:278` after it catches `BadPhoto`, which is raised in `photocollage/render.py:98` if `PIL.Image.open` raises an `IOError`. I have added `print(repr(name)) right into the `try` there. When dragging the file into there, I get this output:

    '/home/mu/Bilder/Bilder_Datenbank/2019/20190322-Selbstportrait_RÃ¶merstraÃ\x9fe/IMG_20190322_132051.jpg'

So somehow GTK has screwed with the encoding here. As it is an instance of `str`, it should better be encoded properly. It is weird that a path is `str` and not `bytes`, but if it were a UTF-8 encoded string, it would be okay. The `name` comes from `filelist`, which in turn comes from `photocollage/gtkgui.py:269` as `new_images`. I now need to find where `update_photolist` is called:

```
$ git grep -n update_photolist
photocollage/gtkgui.py:261:        self.update_photolist([])
photocollage/gtkgui.py:263:    def update_photolist(self, new_images):
photocollage/gtkgui.py:294:            self.update_photolist(files)
photocollage/gtkgui.py:308:        self.update_photolist(files)
photocollage/gtkgui.py:826:        win.update_photolist(sys.argv[1:])
```

The two interesting functions are `choose_images` and `on_drag`. I will now try whether the file chooser gives the same error. And it does not! Using the file selector I get the proper filename from that `print(repr(name))`:

    '/home/mu/Bilder/Bilder_Datenbank/2019/20190322-Selbstportrait_Römerstraße/IMG_20190322_132051.jpg'

And indeed my selfie shows up in the collage. It means that the drop is broken. Adding some more debug output to your code I found that dragging from the KDE file manager Dolphin gives a `TARGET_TYPE_TEXT` and the `files` list contains something with an incorrect encoding:

    ['file:///home/mu/Bilder/Bilder_Datenbank/2019/20190322-Selbstportrait_RÃ¶merstraÃ\x9fe/IMG_20190322_132051.jpg']

Now we *could* this issue by doing the following:

```python
file.encode('latin1').decode('utf8')
```

And if any of that fails we could just ignore that. But I have the hunch that your program should not have to care about this and that the drag and drop encoding is something that goes wrong somewhere here. Either it is Dolphin, the KDE session, or something else. Your program just takes the path given and I would think that your program is fine. Either it is a bug in GTK or some of the KDE libraries. Adding a workaround into your program does not seem appropriate.

I can just use the file chooser for these files. And perhaps some day this issue will be found by the people doing either of the frameworks. I doubt that it makes sense to file a bug because it is so unclear where to file it.

**Comment by adrienverge** [comment]
Thanks for the feedback @martin-ueding.

I just did a simple test to confirm what you say. On Fedora 30 / Gnome 3.32.2, I tried to drag the following file from Nautilus (default file explorer on Gnome):

    /tmp/éàôï/Capture\ d’écran\ de\ 2019-01-23\ 08-42-33.png

... and it worked without problem.
