### ISSUE TITLE
Removing photos

### ISSUE THREAD

**Issue by lukacu** [adrienverge/PhotoCollage#7]
It would be nice to have a way of removing photos from collage. For example Ctrl + Shift + mouse click on the photo.

**Comment by adrienverge** [comment]
I like this idea too, and goes along with adding new photos to an existing collage. My answer is the same as for issue #6.

However, I don't like the "keyboard combination + click" option, since few users will notice that it is possible. I'd rather have a small X icon appearing on each photo when the mouse is over it.

**Comment by lukacu** [comment]
Well the trigger for the action can be arbitrary ... I just thought that "keyboard combination + click" would suit the current minimalistic interface.

**Comment by adrienverge** [comment]
Removing photos is now also implemented in the `add_or_remove_photos` branch! If it works for you, I'll merge it into `master`.

I've done it with the X icon, but feel free to implement the "keyboard combination + click" if you like. :-)

**Comment by lukacu** [comment]
Great, so I have tested it and it works in most cases, the only case where it is a bit confusing is when you remove the last photo which results in an empty canvas. Pressing undo button in this case moves you two steps back (where there are still two photos on the page). In my opinion the most logical way would be to go back one step where there is one photo remaining, however, I understand from my inspection of the code that this may not be easy as empty page is not a history item.

Don't worry about the shortcut, it is quite intuitive now :)

**Comment by adrienverge** [comment]
Thanks for pointing this out lukacu! :-)

I made a change that puts the current state "out of history" when deleting the last photo. The user still can go back to the last state by clicking the "undo" button.
