### ISSUE TITLE
Ability to specify dimensions of collage

### ISSUE THREAD

**Issue by ziggystar** [adrienverge/PhotoCollage#9]
Maybe I'm missing something, but as it appears I have no influence on the aspect ratio (and resolution, dpi) of the resulting collage. For creating wallpapers I need to set the dimensions to my screen resolution.

Add two text boxes that specify width and height of the resulting collage.

**Comment by adrienverge** [comment]
The aspect ratio can be coarsely changed using the two buttons with arrows on them. Unfortunately, the collage generation algorithm does not allow ratio to be set more precisely.

You can save the image in the resolution you want, by specifying the saved image width (after clicking the "Save poster" button).
