### ISSUE TITLE
Request for Flatpak Support

### ISSUE THREAD

**Issue by tim-gromeyer** [adrienverge/PhotoCollage#94]
**Description:**
As a user of `PhotoCollage`, I am excited about the potential of Flatpak for enhancing the distribution and availability of software on various Linux distributions. However, I have noticed that `PhotoCollage` is currently not available as a Flatpak package. I would like to kindly request the addition of Flatpak support to make it easier for users like me to install and use `PhotoCollage` on a wider range of Linux distributions.

**Benefits of Flatpak Support:**
- **Distribution Agnostic:** Flatpak packages can run on various Linux distributions without compatibility issues, providing a consistent experience for users.
- **Up-to-Date Software:** Flatpak allows users to access the latest versions of applications, ensuring they can take advantage of new features and bug fixes promptly.
- **Isolated Environment:** Flatpak's sandboxing ensures that the application runs in a secure and isolated environment, enhancing system security and stability.
- **Easy Installation:** Users can install Flatpak packages without worrying about package dependencies and library conflicts, simplifying the installation process.

**Proposed Action:**
I kindly request that the development team consider adding support for Flatpak packaging of `PhotoCollage`. This would involve creating a Flatpak manifest, configuring the necessary build and runtime dependencies, and providing the package through the Flathub repository. If needed, I am willing to assist with testing and providing feedback during the process.

**Additional Information:**
- [Flathub](https://flathub.org/): Flathub is the central repository for distributing Flatpak applications. Adding `PhotoCollage` to Flathub would make it easily accessible to a wider audience.
- [Flatpak Documentation](https://docs.flatpak.org/en/latest/): The Flatpak documentation provides detailed information on how to package applications using Flatpak.

I appreciate your attention to this request and am looking forward to the possibility of enjoying `PhotoCollage` through the convenience and versatility of Flatpak. Please let me know if there's any additional information or assistance needed from my side to facilitate the process.

Thank you for your dedication to improving the accessibility and user experience of `PhotoCollage`.

**Comment by adrienverge** [comment]
Hello Tim,

Thanks for this proposal and the summary of Flatpack features.

This repo does not provide *distribution* support (.rpm, .deb, .exe, snap...). So it doesn't aim to host a Flatpak manifest, nor any manifest for any Linux distribution or packaging system.
However, I encourage you to create a Flatpak package and maintain it, if you'd like to.

**Comment by tim-gromeyer** [comment]
> However, I encourage you to create a Flatpak package and maintain it, if you'd like to.

Okay, I'll try my best. Can I create a pull request and upstream the flatpak manifest file?

Am I allowed to use your name for packaging? (As the developer nane)

**Comment by adrienverge** [comment]
> Okay, I'll try my best.

:tada: :muscle:

> Can I create a pull request and upstream the flatpak manifest file?

Sorry no, distribution and packaging is not supported by this repo.

> Am I allowed to use your name for packaging? (As the developer nane)

Sure no problem (the name only, not the email address).

**Comment by tim-gromeyer** [comment]
There already seems to be a flatpak metadata file in this repo, see https://github.com/adrienverge/PhotoCollage/blob/master/data/photocollage.appdata.xml

**Comment by adrienverge** [comment]
No, this is an AppData file for desktop environment integration.

**Comment by tim-gromeyer** [comment]
> No, this is an AppData file for desktop environment integration.

Looks very similar to a flatpak app manifest file. Definitely a good base to work with!

**Comment by tim-gromeyer** [comment]
Can you test if it is working? [PhotoCollage.flatpak.zip](https://github.com/adrienverge/PhotoCollage/files/12395331/PhotoCollage.flatpak.zip)

For me it doesn't show an icon in the app list

**Comment by tim-gromeyer** [comment]
I created a Pull Reuest (#95) which is needed for Flatpak. Please merge it

**Comment by tim-gromeyer** [comment]
https://flathub.org/apps/io.github.adrienverge.PhotoCollage

**Comment by tim-gromeyer** [comment]
@adrienverge, maybe you can add a link to it in the README?

**Comment by adrienverge** [comment]
Good idea! Can you open a pull request?

**Comment by tim-gromeyer** [comment]
I'm not very good at writing, I prefer if you do it. You just need to link to the website or add the install instructions from the wesite (See arrow done in the Install button)
